version: 2

defaults: &defaults
    working_directory: /tmp/repo
    docker:
        # specify the version you desire here
        - image: rust:1
    environment:
        SAMPLE: "VARIABLE"

print_version: &print_version
    <<: *defaults
    steps:
        - run:
            name: Print toolchain versions
            command: |
                rustc --version
                cargo --version
                rustup --version

build: &build
    <<: *defaults
    steps:
        - checkout

        - restore_cache:
            keys:
                - v1-dependencies-rust-{{ checksum "Cargo.toml" }}
                - v1-dependencies-rust-

        - run: cargo build

        - save_cache:
            paths:
                - target
            key: v1-dependencies-rust-{{ checksum "Cargo.toml" }}

        - persist_to_workspace:
            root: /tmp
            paths:
                - repo

build_release: &build_release
    <<: *defaults
    steps:
        - checkout

        - restore_cache:
            keys:
                - v1-dependencies-rust-{{ checksum "Cargo.toml" }}
                - v1-dependencies-rust-

        - run: cargo build --release

        - save_cache:
            paths:
                - target
            key: v1-dependencies-rust-{{ checksum "Cargo.toml" }}

        - persist_to_workspace:
            root: /tmp
            paths:
                - repo

jobs:
    print_version:
        <<: *print_version

    build:
        <<: *build

    build_release:
        <<: *build_release

    fmt:
        <<: *defaults
        steps:
            - attach_workspace:
                at: /tmp
            - run: cargo fmt

    check:
        <<: *defaults
        steps:
            - attach_workspace:
                at: /tmp
            - run: cargo check

    test:
        <<: *defaults
        steps:
            - attach_workspace:
                at: /tmp
            - run: cargo test

    bench:
        <<: *defaults
        steps:
            - attach_workspace:
                at: /tmp
            - run: cargo bench

    deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                at: /tmp
            - run: echo todo
workflows:
    version: 2
    test:
        jobs:
            - print_version
            - build
            - build_release
            - fmt:
                requires:
                    - build
            - check:
                requires:
                    - build
            - test:
                requires:
                    - build
            - bench:
                requires:
                    - build_release
            - deploy:
                requires:
                    - build
                    - build_release
                    - fmt
                    - check
                    - test
                    - bench
                filters:
                    branches:
                        only: master